"""
Build canonical NegCtrl gene-weight files from raw genebass burden data.

Outputs `dat/GeneWeights/NegCtrl_{HDL,Alanine,RBC,IBD}.gw.csv`, format:
    Entrez_ID,weight    (no header; weight = abs(BETA Burden))

Selection: the EXACT same Entrez IDs as the previous (uniform-weighted) production
files preserved in `dat/GeneWeights/_archive_pre_beta/NegCtrl_<trait>.uniform.gw.csv`.
This guarantees the only change vs the prior production analysis is the weight column
(1.0 → abs(BETA Burden)). For traits where some archived Entrez IDs lack a current
β value in genebass, those rows are dropped.

These 4 traits are the negative controls presented in the revised manuscript:
- HDL Cholesterol           (genebass continuous trait 30760, irnt)
- Alanine aminotransferase  (genebass continuous trait 30620, irnt)
- Red Blood Cell distrib.   (genebass continuous trait 30070, irnt)
- Inflammatory Bowel Disease(genebass categorical trait IBD_custom2)

Other genebass traits we tested but excluded from the manuscript (T2D, HbA1c,
Parkinson, Alzheimer) are NOT regenerated by this script — see
`docs/plans/2026-05-13-negctrl-beta-vs-uniform.md` for rationale (T2D/Parkinson
introduce neuronal signal; HbA1c shows borderline behavior; all are clinically
linked to cognition or neurodegeneration so cannot serve as clean negative
controls). Their (uniform-weighted) versions remain in `dat/GeneWeights/` for
reproducibility but are not included in main figures.

Previous (uniform-weighted) versions were archived to
`dat/GeneWeights/_archive_pre_beta/NegCtrl_{trait}.uniform.gw.csv` on 2026-05-13.

Usage:
    conda activate gencic
    python scripts/build_negctrl_geneweights.py
"""

import sys
from pathlib import Path
import pandas as pd

PROJ_DIR = Path("/home/jw3514/Work/CellType_Psy/CellTypeBias_VIP")
GW_DIR = PROJ_DIR / "dat" / "GeneWeights"
CTRL_DIR = PROJ_DIR / "dat" / "CTRL"

sys.path.insert(0, str(PROJ_DIR / "src"))
from CellType_PSY import LoadGeneINFO

HGNC, ENSID2Entrez, GeneSymbol2Entrez, Entrez2Symbol = LoadGeneINFO()

NEGCTRL_MAP = {
    "NegCtrl_HDL":     CTRL_DIR / "gene-burden-results-exomes_pLoF_continuous-30760-both_sexes--irnt_2025_11_25_15_49_42.csv",
    "NegCtrl_Alanine": CTRL_DIR / "gene-burden-results-exomes_pLoF_continuous-30620-both_sexes--irnt_2025_12_16_20_18_07.csv",
    "NegCtrl_RBC":     CTRL_DIR / "gene-burden-results-exomes_pLoF_continuous-30070-both_sexes--irnt_2025_12_16_20_41_11.csv",
    "NegCtrl_IBD":     CTRL_DIR / "gene-burden-results-exomes_pLoF_categorical-IBD_custom2-both_sexes--custom_2025_11_25_16_13_49.csv",
}
ARCHIVE_DIR = GW_DIR / "_archive_pre_beta"

print("=" * 78)
print("Building canonical NegCtrl gene-weight files")
print("Gene set = same Entrez IDs as the archived uniform files; weight = abs(BETA Burden)")
print("=" * 78)
print(f"{'name':<22} {'n_archive':>10} {'n_written':>10} {'β_min':>10} {'β_max':>10}")
print("-" * 78)

for setname, raw_path in NEGCTRL_MAP.items():
    archive_file = ARCHIVE_DIR / f"{setname}.uniform.gw.csv"
    archive_df = pd.read_csv(archive_file, header=None, names=["Entrez_ID", "weight"])
    n_archive = len(archive_df)

    raw = pd.read_csv(raw_path)
    bcol = next(c for c in raw.columns if "BETA" in c and "Burden" in c)
    raw["EntrezID"] = raw["Gene Name"].map(
        lambda x: int(GeneSymbol2Entrez[x]) if x in GeneSymbol2Entrez and pd.notnull(GeneSymbol2Entrez.get(x)) else None
    )
    eid2beta = dict(zip(raw["EntrezID"].dropna().astype(int), raw[bcol]))

    rows_out = []
    n_missing = 0
    for eid in archive_df["Entrez_ID"].astype(int):
        beta = eid2beta.get(eid)
        if beta is None or pd.isna(beta):
            n_missing += 1
            continue
        rows_out.append((eid, abs(float(beta))))

    out_df = pd.DataFrame(rows_out, columns=["Entrez_ID", "weight"])
    out_path = GW_DIR / f"{setname}.gw.csv"
    out_df.to_csv(out_path, header=False, index=False)

    n = len(out_df)
    print(f"{setname:<22} {n_archive:>10} {n:>10} {out_df['weight'].min():>10.4f} {out_df['weight'].max():>10.4f}"
          + (f"  ({n_missing} dropped)" if n_missing else ""))

print()
print("Verify:")
for setname in NEGCTRL_MAP:
    p = GW_DIR / f"{setname}.gw.csv"
    df = pd.read_csv(p, header=None)
    print(f"  {p.relative_to(PROJ_DIR)}: {len(df)} rows, weight range [{df[1].min():.4f}, {df[1].max():.4f}]")
